### ISSUE TITLE
Normalize the company wide naming the OSE/Clearinghouse to Clearinghouse

### ISSUE THREAD

**Issue by neodaoist** [valorem-labs-inc/valorem-core#179]
**What:** Decide upon and standardize across all code components on option settlement engine, composed of an underwriting system and clearinghouse.
**Why:** To use ubiquitous language throughout the company and set the stage for productizing Valorem Options as an infrastructure product.

**Comment by 0xAlcibiades** [comment]
We should probably just call it the Valorem Options Clearinghouse, and there's going to be a bunch of standardization throughout materials and code for that.
