### ISSUE TITLE
Update Clearinghouse litepaper and docs

### ISSUE THREAD

**Issue by neodaoist** [valorem-labs-inc/valorem-core#194]
What: Get the litepaper, Solidity docs, and subgraph docs for Clearinghouse in a good way
Why: To have excellent DevEx

**Comment by 0xAlcibiades** [comment]
I'm not sure they are in a bad way now, but an update/review timeboxed to 3-4 hours wouldn't hurt to be sure.

**Comment by neodaoist** [comment]
Closing as dupe of #182
