### ISSUE TITLE
Full test coverage on IOptionSettlementEngine with fuzzing

### ISSUE THREAD

**Issue by 0xAlcibiades** [valorem-labs-inc/valorem-core#23]
The requirement is to use IOptionSettlementEngine and IERC1155, ignoring the internals of the OptionSettlementEngine, to black box test the settlement layer.

**Comment by 0xAlcibiades** [comment]
We can co-work here to get the tests back in place with the new interface.

**Comment by cranium7811** [comment]
I'm almost done with all the tests. will push it in sometime.

**Comment by 0xAlcibiades** [comment]
Some of this was addressed in #27, but need to examine and see if we have full coverage still.

**Comment by 0xAlcibiades** [comment]
I still need to go through line by line and check coverage, but it's looking pretty good now.

**Comment by 0xAlcibiades** [comment]
The coverage here is actually already at 100% according to foundry/forge.
