### ISSUE TITLE
`underlying` returning incorrect asset quantities

### ISSUE THREAD

**Issue by 0xAlcibiades** [valorem-labs-inc/valorem-core#50]

**Comment by Flip-Liquid** [comment]
@0xAlcibiades @thal0x can you provide some detail about what is being returned incorrectly here?

**Comment by Flip-Liquid** [comment]
ping @0xAlcibiades @thal0x, could you share what the expected and actual values were here? I can debug from there. I could DIY but it would take a bit longer.

**Comment by Flip-Liquid** [comment]
missed this the first time through, but looks like there was a little switcheroo in the assignments of the underlying fields: 

![image](https://user-images.githubusercontent.com/13227294/196247453-39dab391-175d-4ca8-bb37-3ef06fabc761.png)

**Comment by Flip-Liquid** [comment]
i.e. exerciseAmount being assigned to underlying position, vice versa
