### ISSUE TITLE
RFC: Valorem does not support fee on transfer tokens

### ISSUE THREAD

**Issue by supernovahs** [valorem-labs-inc/valorem-core#66]
https://github.com/valorem-labs-inc/valorem-core/blob/42d8c11c7c9db5ee777587f27c7b84edc7498a97/src/OptionSettlement.sol#L341

Protocol will receive less amount than should be received, you should consider using change in balance as a way to update state.

**Comment by supernovahs** [comment]
Similar instances in other places also

**Comment by supernovahs** [comment]
@thal0x

**Comment by 0xAlcibiades** [comment]
@supernovahs I think we explicitly called out in the litepaper not supporting fee on transfer tokens. I think we can add some balance assertions to explicitly disallow their use in the protocol. That said, people can devise all sorts of poison tokens, and I think we'd likely just block them in the frontend and call out the fact that they aren't supported in the docs. I'm of the mind that a fee on transfer token is not something we want/need to support. I also think there is a near 0 chance it would ever be added to USDC.

**Comment by albertocevallos** [comment]
> people can devise all sorts of poison tokens, and I think we'd likely just block them in the frontend

On that note, we should setup a [custom token list](https://github.com/Uniswap/token-lists#authoring-token-lists) using the [tokenlists.org](https://tokenlists.org/) standard from Uniswap - as the primary poison token filter for the frontend.

**Comment by supernovahs** [comment]
Sounds good.
In case this helps
https://blog.1inch.io/balancer-hack-2020-a8f7131c980e
