### ISSUE TITLE
token URI test emission assertion

### ISSUE THREAD

**Issue by Flip-Liquid** [valorem-labs-inc/valorem-core#73]
testTokenURI does not assert the return value of the test optionId

**Comment by 0xAlcibiades** [comment]
@Flip-Liquid @neodaoist I think we should add an adapter for tokenURI which points at another contract, or even better, library, to generate the URI. That's the least tested part of the code, and we should decouple it. Plus adds flexibility down the line.

**Comment by 0xAlcibiades** [comment]
Nixing this, could introduce vulnerability, fine the way it is.
