### ISSUE TITLE
DRY events for testing

### ISSUE THREAD

**Issue by Flip-Liquid** [valorem-labs-inc/valorem-core#75]
events are redefined in OptionSettlement.t.sol that are in IOptionSettlementEngine. Consider removing this redefinition.

**Comment by 0xAlcibiades** [comment]
Not a big deal, closing.

**Comment by 0xAlcibiades** [comment]
Actually, on 2nd thought, should be a really easy fix.

**Comment by neodaoist** [comment]
Closing for now, will re-open if we want to pull events into a Library
