### ISSUE TITLE
Investigate test reverts

### ISSUE THREAD

**Issue by Flip-Liquid** [valorem-labs-inc/valorem-core#77]
testFailNewOptionTypeOptionsTypeExists
// TODO: investigate this revert - OptionsChainExists error should be displayed
//  with an argument, implying this expectRevert would use `abi.encodeWithSelector();

testExerciseWithDifferentDecimals test fails with an InvalidAssets() error

**Comment by 0xAlcibiades** [comment]
@Flip-Liquid we should fix these tests.
