### ISSUE TITLE
Change underlying container type of ClaimBuckets from map to array

### ISSUE THREAD

**Issue by Flip-Liquid** [valorem-labs-inc/valorem-core#79]
ClaimBuckets correspond to individual days. Written options are thrown into the ClaimBuckets. A map from timestamp or day to ClaimBuckets is potentially sparse.  There may be days on which zero options are written for a given option type.

e.g.: an option is created with a 3M expiry timestamp. options are written on days 1, 60, and 89. The assignment process, while still being capped at O(days) would iterate days 1-89 seeking to assign options in each bucket for those days, even though the only buckets with options are on days 1, 60, 89.

An array fixes this issue, since they're inherently densely packed. Only days 1, 60, 89 would be considered for the assignment process in the above example.

**Comment by Flip-Liquid** [comment]
@0xAlcibiades we can take this work in #69 but breaking it out here to review and discuss

**Comment by neodaoist** [comment]
Still building my mental model of how claim bucketing works, but this makes sense to me. An array is probably a better data structure to represent this, and could reduce both loop operations and storage.

If I understand, we'd have to move the info of which days had options written onto the ClaimIndex struct directly.

**Comment by Flip-Liquid** [comment]
Yep. 

> If I understand, we'd have to move the info of which days had options written onto the ClaimIndex struct directly.

The claim index already has that field, so the context of how the field used would be changed.

**Comment by Flip-Liquid** [comment]
Closed in #69
