### ISSUE TITLE
Review public accessor methods

### ISSUE THREAD

**Issue by Flip-Liquid** [valorem-labs-inc/valorem-core#82]
option, claim, tokenType accessors need a review after adding 

claimBucket + claimIndex.

Do we also expose accessors to these? Do we think that it would be useful for 
1) options writers/holders to see the amount of options that have been exercised (via accessing buckets)?
2) claimants (options writers) to see the amount of their options lots that have been exercised (via accessing claim indices)?

**Comment by Flip-Liquid** [comment]
Additionally, what checks need to be added to claim, tokenType, option.

**Comment by Flip-Liquid** [comment]
I'll take a look, propose something, and we can review later today @neodaoist @0xAlcibiades

**Comment by Flip-Liquid** [comment]
my take: `_doesBucketIndexHaveUnexercisedOptions `and `_unexercisedBucketsByOption` can be kept as internal without public accessors. assignment is equally likely in every bucket before expiry, and these two are just bookkeeping mappings to ensure this is done efficiently. There is little liklihood that an option writer or holder would get any value from having easier access to these.

While exposing access for `_claimBucketByOption` might at first seem like it might be useful to writers/holders, in order to see what portion of their lot has been exercised, the `underlying()` function already provides this. 

I'm ambivalent as to whether claim holders would find it useful to see which days/buckets they have written into (via exposing _claimIdToClaimIndexArray. 

WDYT @0xAlcibiades @neodaoist ?

**Comment by 0xAlcibiades** [comment]
Let's remove any unneeded public accessors.
