### ISSUE TITLE
More ideas for docs

### ISSUE THREAD

**Issue by 0xAlcibiades** [valorem-labs-inc/valorem-core#98]
deas for more doc, in addition to the current Overview, Building the protocol, and Core interface. Would love feedback on what could be most valuable before the C4A, before I go too far down any path.

    Intro to the Protocol
    Trust Model
        Actors
        Assets
        Actions
    Story Map (visual)
        writer flow (writing, redeeming)
        holder flow (exercising)
    Scenario Descriptions (plain English)
        writer specification
        holder specification
    Invariants
        system-level
        function-level
    Glossary
        quick-hit definitions of key terms
    Security Info
        Audit
        Bug bounty
        Contact info

**Comment by neodaoist** [comment]
Doing this week, after naming+ordering PR

**Comment by 0xAlcibiades** [comment]
@neodaoist we can hold off on the rest of this until after code freeze excluding what's already in #84

**Comment by neodaoist** [comment]
That sounds good
